version: "3.5"

services:
  api-server:
    build: ./back-end/api-server/
    expose:
      - "80"
    networks:
      - hackathon-network
    restart: always

  file-server:
    build: .
    ports:
      - 80:80
      # - 443:443
    networks:
      - hackathon-network
    restart: always

networks:
  hackathon-network:
    name: hackathon-network-network

